blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/sanko/Infix/discussions
    about: Please ask and answer questions here.
  - name: Security Advisories
    url: https://github.com/sanko/Infix/security/advisories/new
    about: Please report security vulnerabilities here.
