name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] A brief, descriptive title"
labels: ["enhancement"]
assignees:
 - sanko
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea to make Infix even better! We welcome high-level suggestions as well as detailed proposals for new ABIs or features.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "e.g., I'm trying to use Infix on the RISC-V architecture, but it's not currently supported."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, research, links to ABI documentation, or screenshots about the feature request here.
