name: Dump Variadic sprintf Assembly

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  dump-asm:
    name: Dump Assembly on ${{ matrix.os }} ARM64
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Create Variadic C Test Case
        run: |
          cat << 'EOF' > harness.c
          #include <stdio.h>

          void make_variadic_call() {
              char buffer[128];
              const char* fmt = "Testing variadic: %s %d %.2f\n";
              const char* str_arg = "hello";
              int int_arg = 123;
              double dbl_arg = 3.14;

              sprintf(buffer, fmt, str_arg, int_arg, dbl_arg);

              printf("%s", buffer);
          }

          int main() {
              make_variadic_call();
              return 0;
          }
          EOF

      - name: Compile to Assembly (-O2)
        run: gcc -O2 -S harness.c -o harness.s

      - name: Display Assembly for ${{ matrix.os }}
        run: |
          echo "--- Assembly for ${{ matrix.os }} ---"
          cat harness.s
          echo "--- End of Assembly ---"
